import tkinter as tk
from tkinter import *
from tkinter import ttk
window = tk.Tk()
window.title("Pokemon Adventure")
window.geometry("600x560")
#Entities
main = tk.PhotoImage(file = "main.png")
screen = tk.Label(window, image = main)
minit = tk.Label(window, text = "Mini Map")
m = tk.PhotoImage(file = "minimap.png")
minimap = tk.Label(window, image = m)
map = tk.Button(window, text = "Map", anchor = CENTER)
inv = tk.Button(window, text = "Inventory", anchor = CENTER)
Dex = tk.Button(window, text = "Pokedex", anchor = CENTER)
Ros = tk.Button(window, text ="Roster", anchor = CENTER)
J = tk.Button(window, text = "Journal", anchor = CENTER)
Hel = tk.Button(window, text = "Help", anchor = CENTER)
Sho = tk.Button(window, text = "Shop", anchor = CENTER)
nin = tk.PhotoImage(file = "logo.png")
logo = tk.Label(window, image = nin)
c = tk.PhotoImage(file = "compass.png")
compass = tk.Label(window, image = c)
#Position
screen.place(x = 20, y = 20, height = 400, width = 433, )
minit.place(x = 500, y = 40)
minimap.place(x=480, y = 60)
map.place(x = 480, y = 160, width = 100, height = 35)
inv.place(x=480, y = 195, width = 100, height = 35)
Dex.place(x=480, y = 230, width = 100, height = 35)
Ros.place(x=480, y = 265, width = 100, height = 35)
J.place(x=480, y = 300, width = 100, height = 35)
Hel.place(x=480, y = 335, width = 100, height = 35)
Sho.place(x=480, y = 370, width = 100, height = 35)
logo.place(x = 300, y = 490,anchor=CENTER)
compass.place(x = 20, y = 540, anchor = SW )
window.mainloop()